version: "3"
services:

  # Postgres
  postgres:
    image: postgres:14
    container_name: fruits-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test

  # Apicurio
  apicurio:
    image: quay.io/apicurio/apicurio-registry-mem:2.4.2.Final
    container_name: fruits-events-registry
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: "true"
      QUARKUS_HTTP_PORT: 8086

  # Kafka
  kafka:
    image: quay.io/strimzi/kafka:0.34.0-kafka-3.4.0
    container_name: fruits-broker
    depends_on:
      - apicurio
    command:
      - "sh"
      - "-c"
      - "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  # Infinispan
  infinispan:
    image: infinispan/server:latest
    container_name: fruits-cache
    restart: always
    ports:
      - "11222:11222"
    environment:
      USER: admin
      PASS: password
